### ISSUE TITLE
Option to inline all assets

### ISSUE THREAD

**Issue by PragTob** [PragTob/benchee_html#11]
An option inline all assets (CSS/JavaScript) would be great. This way the files could be totally independent moved and copied around without worrying that all the appropriate asset folders have to be present.

**Comment by elpikel** [comment]
@PragTob can I take this one?

**Comment by PragTob** [comment]
Sure thing :)

**Comment by elpikel** [comment]
@PragTob please close this one.

**Comment by PragTob** [comment]
I always forget 😅
