### ISSUE TITLE
Write to a default folder/file if none is specified

### ISSUE THREAD

**Issue by PragTob** [PragTob/benchee_html#16]
Like `benchmarks/benchmark.html` - makes for a better first time user experience imo and documentation on how to change it is still there.

**Comment by elpikel** [comment]
can i take this one?

**Comment by PragTob** [comment]
sure thing

**Comment by elpikel** [comment]
Should i add it to pull: https://github.com/PragTob/benchee_html/pull/17 ?

**Comment by PragTob** [comment]
Oh no, rather separate small PRs - sorry for the delay, health has been mediocore so OSS time has been low :)
