### ISSUE TITLE
Make auto opening report in browser configurable

### ISSUE THREAD

**Issue by PragTob** [PragTob/benchee_html#27]
Need a new formatter_option like `auto_open` or something that is either true or false. If it's false `open_report` should just not open the report in a browser.

Most importantly, please set the option to false in all tests so that my test don't open all the browser tabs all the time :D

**Comment by elpikel** [comment]
Working on it.

**Comment by PragTob** [comment]
Sorry, this was already implemented forgot to close the issue my bad sorry :| #30
