### ISSUE TITLE
Memory usage statistics don't appear in the HTML template

### ISSUE THREAD

**Issue by hazardfn** [PragTob/benchee_html#42]
Would be nice if the stats from `memory_time:` were a part of the HTML output :).

**Comment by PragTob** [comment]
It would indeed! :)

Sorry not all of the formatters are up to date - it's one of the bigger things we gotta get to before 1.0 PragTob/benchee#187

**Comment by hazardfn** [comment]
I would offer to help but I have always been more of a backend kind of person, I feel I'd only disappoint you 😛

**Comment by PragTob** [comment]
@hazardfn always room to grow :) It's not _that_ complicated as most of it is data rendered through eex (data tables) - sure a bit of JavaScript would be involved in extracting and generalizing th functions. No pressure though, we'll get to it eventually but of course we love ourselves some help :)

**Comment by PragTob** [comment]
Fixed in 0.6.0 :tada:
