### ISSUE TITLE
Set custom y0 for raw run time charts

### ISSUE THREAD

**Issue by PragTob** [PragTob/benchee_html#7]
Right now the raw run time charts all go up to a certain level which is understandable as there is a minimum execution time. I think it'd be better if benchee_html set a custom start value for the y-axis that is something like minimum - 10% * minimum so that the height of the chart is used more effectively to show the differences.

what might help here from plotly.js (oe well hopefully will) is setting [y0](https://plot.ly/javascript/reference/#bar-y0).

Example of what's "broken":

![image](https://camo.githubusercontent.com/f65b5331c2c8227a94f682a08e2a14e7191f7149/687474703a2f2f7777772e70726167746f622e696e666f2f62656e636865652f696d616765732f7261775f72756e5f74696d65732e706e67)

**Comment by kinson** [comment]
I think this issue can be closed now, should another be opened to write tests for the minimum y?
